name: Update README Data

on:
  schedule:
    - cron: '0 0 * * *'  # Roz raat 12 baje (UTC time)
  workflow_dispatch:      # Manual trigger ke liye

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Run Python Script
        run: python today.py
        
      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto update profile data"
          git push
